name: Store build artifacts
description: Stores the build artifacts for later inspection
runs:
  using: "composite"
  steps:
    - name: Store APKs
      uses: actions/upload-artifact@v4
      with:
        name: apks
        path: '**/*.apk'
    - name: Store reports
      uses: actions/upload-artifact@v4
      with:
        name: reports
        path: '**/build/reports/**'