/*
 * Copyright (C) 2024 Niall 'Rivernile' Scott
 *
 * This software is provided 'as-is', without any express or implied
 * warranty.  In no event will the authors or contributors be held liable for
 * any damages arising from the use of this software.
 *
 * The aforementioned copyright holder(s) hereby grant you a
 * non-transferrable right to use this software for any purpose (including
 * commercial applications), and to modify it and redistribute it, subject to
 * the following conditions:
 *
 *  1. This notice may not be removed or altered from any file it appears in.
 *
 *  2. Any modifications made to this software, except those defined in
 *     clause 3 of this agreement, must be released under this license, and
 *     the source code of any modifications must be made available on a
 *     publically accessible (and locateable) website, or sent to the
 *     original author of this software.
 *
 *  3. Software modifications that do not alter the functionality of the
 *     software but are simply adaptations to a specific environment are
 *     exempt from clause 2.
 *
 */

package uk.org.rivernile.android.bustracker.ui.theme

import androidx.compose.ui.graphics.Color

/*
 * Material 3 colours
 *
 * Primary: #C41411
 * Secondary: #AE8882
 * Tertiary: #6D3465
 * Neutral: #998E8D
 */

internal val primaryLight = Color(0xFF904A41)
internal val onPrimaryLight = Color(0xFFFFFFFF)
internal val primaryContainerLight = Color(0xFFFFDAD5)
internal val onPrimaryContainerLight = Color(0xFF3B0906)
internal val secondaryLight = Color(0xFF904B40)
internal val onSecondaryLight = Color(0xFFFFFFFF)
internal val secondaryContainerLight = Color(0xFFFFDAD4)
internal val onSecondaryContainerLight = Color(0xFF3A0905)
internal val tertiaryLight = Color(0xFF814D78)
internal val onTertiaryLight = Color(0xFFFFFFFF)
internal val tertiaryContainerLight = Color(0xFFFFD7F3)
internal val onTertiaryContainerLight = Color(0xFF340831)
internal val errorLight = Color(0xFFBA1A1A)
internal val onErrorLight = Color(0xFFFFFFFF)
internal val errorContainerLight = Color(0xFFFFDAD6)
internal val onErrorContainerLight = Color(0xFF410002)
internal val backgroundLight = Color(0xFFFFF8F7)
internal val onBackgroundLight = Color(0xFF231918)
internal val surfaceLight = Color(0xFFFFF8F7)
internal val onSurfaceLight = Color(0xFF231919)
internal val surfaceVariantLight = Color(0xFFF5DDDA)
internal val onSurfaceVariantLight = Color(0xFF534341)
internal val outlineLight = Color(0xFF857370)
internal val outlineVariantLight = Color(0xFFD8C2BE)
internal val scrimLight = Color(0xFF000000)
internal val inverseSurfaceLight = Color(0xFF382E2D)
internal val inverseOnSurfaceLight = Color(0xFFFFEDEB)
internal val inversePrimaryLight = Color(0xFFFFB4A9)
internal val surfaceDimLight = Color(0xFFE8D6D4)
internal val surfaceBrightLight = Color(0xFFFFF8F7)
internal val surfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val surfaceContainerLowLight = Color(0xFFFFF0EF)
internal val surfaceContainerLight = Color(0xFFFCEAE8)
internal val surfaceContainerHighLight = Color(0xFFF6E4E2)
internal val surfaceContainerHighestLight = Color(0xFFF1DEDD)

internal val primaryLightMediumContrast = Color(0xFF6E3028)
internal val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
internal val primaryContainerLightMediumContrast = Color(0xFFAA6056)
internal val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val secondaryLightMediumContrast = Color(0xFF6E3027)
internal val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
internal val secondaryContainerLightMediumContrast = Color(0xFFAA6055)
internal val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val tertiaryLightMediumContrast = Color(0xFF62315B)
internal val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
internal val tertiaryContainerLightMediumContrast = Color(0xFF9A628F)
internal val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val errorLightMediumContrast = Color(0xFF8C0009)
internal val onErrorLightMediumContrast = Color(0xFFFFFFFF)
internal val errorContainerLightMediumContrast = Color(0xFFDA342E)
internal val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val backgroundLightMediumContrast = Color(0xFFFFF8F7)
internal val onBackgroundLightMediumContrast = Color(0xFF231918)
internal val surfaceLightMediumContrast = Color(0xFFFFF8F7)
internal val onSurfaceLightMediumContrast = Color(0xFF231919)
internal val surfaceVariantLightMediumContrast = Color(0xFFF5DDDA)
internal val onSurfaceVariantLightMediumContrast = Color(0xFF4F3F3D)
internal val outlineLightMediumContrast = Color(0xFF6C5B59)
internal val outlineVariantLightMediumContrast = Color(0xFF897674)
internal val scrimLightMediumContrast = Color(0xFF000000)
internal val inverseSurfaceLightMediumContrast = Color(0xFF382E2D)
internal val inverseOnSurfaceLightMediumContrast = Color(0xFFFFEDEB)
internal val inversePrimaryLightMediumContrast = Color(0xFFFFB4A9)
internal val surfaceDimLightMediumContrast = Color(0xFFE8D6D4)
internal val surfaceBrightLightMediumContrast = Color(0xFFFFF8F7)
internal val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
internal val surfaceContainerLowLightMediumContrast = Color(0xFFFFF0EF)
internal val surfaceContainerLightMediumContrast = Color(0xFFFCEAE8)
internal val surfaceContainerHighLightMediumContrast = Color(0xFFF6E4E2)
internal val surfaceContainerHighestLightMediumContrast = Color(0xFFF1DEDD)

internal val primaryLightHighContrast = Color(0xFF44100B)
internal val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
internal val primaryContainerLightHighContrast = Color(0xFF6E3028)
internal val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val secondaryLightHighContrast = Color(0xFF44100A)
internal val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
internal val secondaryContainerLightHighContrast = Color(0xFF6E3027)
internal val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val tertiaryLightHighContrast = Color(0xFF3C1038)
internal val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
internal val tertiaryContainerLightHighContrast = Color(0xFF62315B)
internal val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val errorLightHighContrast = Color(0xFF4E0002)
internal val onErrorLightHighContrast = Color(0xFFFFFFFF)
internal val errorContainerLightHighContrast = Color(0xFF8C0009)
internal val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
internal val backgroundLightHighContrast = Color(0xFFFFF8F7)
internal val onBackgroundLightHighContrast = Color(0xFF231918)
internal val surfaceLightHighContrast = Color(0xFFFFF8F7)
internal val onSurfaceLightHighContrast = Color(0xFF000000)
internal val surfaceVariantLightHighContrast = Color(0xFFF5DDDA)
internal val onSurfaceVariantLightHighContrast = Color(0xFF2E211F)
internal val outlineLightHighContrast = Color(0xFF4F3F3D)
internal val outlineVariantLightHighContrast = Color(0xFF4F3F3D)
internal val scrimLightHighContrast = Color(0xFF000000)
internal val inverseSurfaceLightHighContrast = Color(0xFF382E2D)
internal val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
internal val inversePrimaryLightHighContrast = Color(0xFFFFE7E3)
internal val surfaceDimLightHighContrast = Color(0xFFE8D6D4)
internal val surfaceBrightLightHighContrast = Color(0xFFFFF8F7)
internal val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
internal val surfaceContainerLowLightHighContrast = Color(0xFFFFF0EF)
internal val surfaceContainerLightHighContrast = Color(0xFFFCEAE8)
internal val surfaceContainerHighLightHighContrast = Color(0xFFF6E4E2)
internal val surfaceContainerHighestLightHighContrast = Color(0xFFF1DEDD)

internal val primaryDark = Color(0xFFFFB4A9)
internal val onPrimaryDark = Color(0xFF561E17)
internal val primaryContainerDark = Color(0xFF73342C)
internal val onPrimaryContainerDark = Color(0xFFFFDAD5)
internal val secondaryDark = Color(0xFFFFB4A8)
internal val onSecondaryDark = Color(0xFF561E17)
internal val secondaryContainerDark = Color(0xFF73342B)
internal val onSecondaryContainerDark = Color(0xFFFFDAD4)
internal val tertiaryDark = Color(0xFFF3B3E4)
internal val onTertiaryDark = Color(0xFF4D1F47)
internal val tertiaryContainerDark = Color(0xFF66355F)
internal val onTertiaryContainerDark = Color(0xFFFFD7F3)
internal val errorDark = Color(0xFFFFB4AB)
internal val onErrorDark = Color(0xFF690005)
internal val errorContainerDark = Color(0xFF93000A)
internal val onErrorContainerDark = Color(0xFFFFDAD6)
internal val backgroundDark = Color(0xFF1A1110)
internal val onBackgroundDark = Color(0xFFF1DEDC)
internal val surfaceDark = Color(0xFF1A1111)
internal val onSurfaceDark = Color(0xFFF1DEDD)
internal val surfaceVariantDark = Color(0xFF534341)
internal val onSurfaceVariantDark = Color(0xFFD8C2BE)
internal val outlineDark = Color(0xFFA08C89)
internal val outlineVariantDark = Color(0xFF534341)
internal val scrimDark = Color(0xFF000000)
internal val inverseSurfaceDark = Color(0xFFF1DEDD)
internal val inverseOnSurfaceDark = Color(0xFF382E2D)
internal val inversePrimaryDark = Color(0xFF904A41)
internal val surfaceDimDark = Color(0xFF1A1111)
internal val surfaceBrightDark = Color(0xFF423736)
internal val surfaceContainerLowestDark = Color(0xFF140C0C)
internal val surfaceContainerLowDark = Color(0xFF231919)
internal val surfaceContainerDark = Color(0xFF271D1D)
internal val surfaceContainerHighDark = Color(0xFF322827)
internal val surfaceContainerHighestDark = Color(0xFF3D3231)

internal val primaryDarkMediumContrast = Color(0xFFFFBAB0)
internal val onPrimaryDarkMediumContrast = Color(0xFF330503)
internal val primaryContainerDarkMediumContrast = Color(0xFFCC7B70)
internal val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
internal val secondaryDarkMediumContrast = Color(0xFFFFBAAF)
internal val onSecondaryDarkMediumContrast = Color(0xFF330502)
internal val secondaryContainerDarkMediumContrast = Color(0xFFCC7B6F)
internal val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
internal val tertiaryDarkMediumContrast = Color(0xFFF7B7E8)
internal val onTertiaryDarkMediumContrast = Color(0xFF2E032B)
internal val tertiaryContainerDarkMediumContrast = Color(0xFFB87EAC)
internal val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
internal val errorDarkMediumContrast = Color(0xFFFFBAB1)
internal val onErrorDarkMediumContrast = Color(0xFF370001)
internal val errorContainerDarkMediumContrast = Color(0xFFFF5449)
internal val onErrorContainerDarkMediumContrast = Color(0xFF000000)
internal val backgroundDarkMediumContrast = Color(0xFF1A1110)
internal val onBackgroundDarkMediumContrast = Color(0xFFF1DEDC)
internal val surfaceDarkMediumContrast = Color(0xFF1A1111)
internal val onSurfaceDarkMediumContrast = Color(0xFFFFF9F9)
internal val surfaceVariantDarkMediumContrast = Color(0xFF534341)
internal val onSurfaceVariantDarkMediumContrast = Color(0xFFDCC6C2)
internal val outlineDarkMediumContrast = Color(0xFFB39E9B)
internal val outlineVariantDarkMediumContrast = Color(0xFF927F7C)
internal val scrimDarkMediumContrast = Color(0xFF000000)
internal val inverseSurfaceDarkMediumContrast = Color(0xFFF1DEDD)
internal val inverseOnSurfaceDarkMediumContrast = Color(0xFF322827)
internal val inversePrimaryDarkMediumContrast = Color(0xFF74352D)
internal val surfaceDimDarkMediumContrast = Color(0xFF1A1111)
internal val surfaceBrightDarkMediumContrast = Color(0xFF423736)
internal val surfaceContainerLowestDarkMediumContrast = Color(0xFF140C0C)
internal val surfaceContainerLowDarkMediumContrast = Color(0xFF231919)
internal val surfaceContainerDarkMediumContrast = Color(0xFF271D1D)
internal val surfaceContainerHighDarkMediumContrast = Color(0xFF322827)
internal val surfaceContainerHighestDarkMediumContrast = Color(0xFF3D3231)

internal val primaryDarkHighContrast = Color(0xFFFFF9F8)
internal val onPrimaryDarkHighContrast = Color(0xFF000000)
internal val primaryContainerDarkHighContrast = Color(0xFFFFBAB0)
internal val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
internal val secondaryDarkHighContrast = Color(0xFFFFF9F8)
internal val onSecondaryDarkHighContrast = Color(0xFF000000)
internal val secondaryContainerDarkHighContrast = Color(0xFFFFBAAF)
internal val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
internal val tertiaryDarkHighContrast = Color(0xFFFFF9FA)
internal val onTertiaryDarkHighContrast = Color(0xFF000000)
internal val tertiaryContainerDarkHighContrast = Color(0xFFF7B7E8)
internal val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
internal val errorDarkHighContrast = Color(0xFFFFF9F9)
internal val onErrorDarkHighContrast = Color(0xFF000000)
internal val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
internal val onErrorContainerDarkHighContrast = Color(0xFF000000)
internal val backgroundDarkHighContrast = Color(0xFF1A1110)
internal val onBackgroundDarkHighContrast = Color(0xFFF1DEDC)
internal val surfaceDarkHighContrast = Color(0xFF1A1111)
internal val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
internal val surfaceVariantDarkHighContrast = Color(0xFF534341)
internal val onSurfaceVariantDarkHighContrast = Color(0xFFFFF9F8)
internal val outlineDarkHighContrast = Color(0xFFDCC6C2)
internal val outlineVariantDarkHighContrast = Color(0xFFDCC6C2)
internal val scrimDarkHighContrast = Color(0xFF000000)
internal val inverseSurfaceDarkHighContrast = Color(0xFFF1DEDD)
internal val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
internal val inversePrimaryDarkHighContrast = Color(0xFF4E1812)
internal val surfaceDimDarkHighContrast = Color(0xFF1A1111)
internal val surfaceBrightDarkHighContrast = Color(0xFF423736)
internal val surfaceContainerLowestDarkHighContrast = Color(0xFF140C0C)
internal val surfaceContainerLowDarkHighContrast = Color(0xFF231919)
internal val surfaceContainerDarkHighContrast = Color(0xFF271D1D)
internal val surfaceContainerHighDarkHighContrast = Color(0xFF322827)
internal val surfaceContainerHighestDarkHighContrast = Color(0xFF3D3231)

