name: Enable hardware acceleration
description: Enables hardware acceleration on GitHub Actions runners
runs:
  using: "composite"
  steps:
    - name: Enable hardware acceleration
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
