name: Write keystore file
description: Writes the keystore file to use for the build
inputs:
  keystore-file-base64:
    description: The keystore file encoded as Base64
    required: true
outputs:
  keystore-path:
    description: The path to the keystore
    value: ${{ steps.write-keystore.outputs.keystore-path }}
runs:
  using: "composite"
  steps:
    - name: Write keystore
      id: write-keystore
      run: |
        echo ${{ inputs.keystore-file-base64 }} | base64 --decode > $KEYSTORE_FILE
        echo "keystore-path=$KEYSTORE_FILE" >> $GITHUB_OUTPUT
      shell: bash
      env:
        KEYSTORE_FILE: ${{ runner.temp }}/key.keystore