name: Prune disk usage
description: Prunes disk usage to leave enough space for this project to build and test
runs:
  using: "composite"
  steps:
    - name: Prune disk usage
      run: |
        sudo rm -rf /usr/share/dotnet /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        sudo docker builder prune -a
      shell: bash
