/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package uk.org.rivernile.edinburghbustracker.android;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int enterstopcode_entry=0x7f050001;
        public static final int enterstopcode_label=0x7f050000;
        public static final int enterstopcode_submit=0x7f050002;
    }
    public static final class layout {
        public static final int displaystopdata=0x7f020000;
        public static final int enterstopcode=0x7f020001;
        public static final int favouritestops=0x7f020002;
    }
    public static final class string {
        public static final int app_description=0x7f040001;
        /**  Application strings 
         */
        public static final int app_name=0x7f040000;
        public static final int app_version=0x7f040002;
        public static final int cancel=0x7f040008;
        public static final int displaystopdata_empty=0x7f040016;
        public static final int displaystopdata_err_nocode=0x7f040017;
        public static final int displaystopdata_err_noconn=0x7f040019;
        public static final int displaystopdata_err_nodata=0x7f04001c;
        public static final int displaystopdata_err_noresolv=0x7f04001a;
        public static final int displaystopdata_err_parseerr=0x7f040018;
        public static final int displaystopdata_err_serverr=0x7f04001b;
        public static final int displaystopdata_gettingdata=0x7f040015;
        public static final int displaystopdata_menu_addfav=0x7f040020;
        public static final int displaystopdata_menu_refresh=0x7f04001f;
        public static final int displaystopdata_menu_remfac=0x7f040021;
        public static final int displaystopdata_menu_turnautorefreshoff=0x7f04001e;
        /**  Strings for DisplayStopDataActivity menu 
         */
        public static final int displaystopdata_menu_turnautorefreshon=0x7f04001d;
        /**  Strings for DisplayStopDataActivity 
         */
        public static final int displaystopdata_title=0x7f040013;
        public static final int displaystopdata_title2=0x7f040014;
        public static final int enterstopcode_edit_hint=0x7f040010;
        public static final int enterstopcode_text=0x7f04000e;
        /**  Strings for EnterStopCodeActivity 
         */
        public static final int enterstopcode_title=0x7f04000d;
        public static final int enterstopcode_toast_inputerr=0x7f04000f;
        public static final int error=0x7f040006;
        /**  Generic strings 
         */
        public static final int exit=0x7f040003;
        public static final int favouritestops_nosavedstops=0x7f040012;
        /**  Strings for FavouriteStopsActivity 
         */
        public static final int favouritestops_title=0x7f040011;
        public static final int main_bus_stop_map=0x7f04000c;
        public static final int main_enter_stop_code=0x7f04000b;
        /**  Strings for MainActivity 
         */
        public static final int main_favourite_stops=0x7f04000a;
        public static final int okay=0x7f040007;
        public static final int preferences=0x7f040005;
        public static final int preferences_category_autorefresh=0x7f040025;
        public static final int preferences_category_server=0x7f040027;
        public static final int preferences_checkbox_autorefresh_summary=0x7f040026;
        public static final int preferences_invalidhostname=0x7f040023;
        public static final int preferences_invalidport=0x7f040024;
        public static final int preferences_textbox_hostname=0x7f040028;
        public static final int preferences_textbox_hostname_dialog=0x7f04002a;
        public static final int preferences_textbox_hostname_summary=0x7f040029;
        public static final int preferences_textbox_port=0x7f04002b;
        public static final int preferences_textbox_port_dialog=0x7f04002d;
        public static final int preferences_textbox_port_summary=0x7f04002c;
        /**  Strings for PreferencesActivity 
         */
        public static final int preferences_title=0x7f040022;
        public static final int retry=0x7f040009;
        public static final int submit=0x7f040004;
    }
    public static final class xml {
        public static final int preferences=0x7f030000;
    }
}
