/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package uk.org.rivernile.edinburghbustracker.android;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int enterstopcode_entry=0x7f050001;
        public static final int enterstopcode_label=0x7f050000;
        public static final int enterstopcode_submit=0x7f050002;
        public static final int main_menu_addstop=0x7f050005;
        public static final int main_menu_exit=0x7f050006;
        public static final int main_menu_map=0x7f050004;
        public static final int main_menu_stopcode=0x7f050003;
    }
    public static final class layout {
        public static final int enterstopcode=0x7f020000;
        public static final int main=0x7f020001;
    }
    public static final class menu {
        public static final int mainmenu=0x7f040000;
    }
    public static final class string {
        public static final int app_description=0x7f030001;
        /**  Application strings 
         */
        public static final int app_name=0x7f030000;
        public static final int app_version=0x7f030002;
        public static final int enterstopcode_text=0x7f030009;
        /** Strings for EnterStopCodeActivity 
         */
        public static final int enterstopcode_title=0x7f030008;
        /**  Generic strings 
         */
        public static final int exit=0x7f030003;
        public static final int main_menu_addstop=0x7f030007;
        public static final int main_menu_map=0x7f030006;
        /**  Strings for MainActivity 
 Strings for MainActivity menu 
         */
        public static final int main_menu_stopcode=0x7f030005;
        public static final int submit=0x7f030004;
    }
}
